#!/usr/bin/env python
#
# Copyright (c) 2023 Autonomous Driving Lab (ADL), University of Tartu.
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.
"""
receive :CarlaEgoVehicleStatus and publishes autoware_msgs::VehicleStatus
"""
import math
import rospy
from carla_msgs.msg import CarlaEgoVehicleInfo
from carla_msgs.msg import CarlaEgoVehicleStatus
from autoware_msgs.msg import VehicleStatus, Gear


class CarlaVehicleStatusPublisher:

    def __init__(self):
        # Node parameters
        self.max_steer_angle = math.radians(rospy.get_param("~max_steer_angle", default=70))

        # Publishers
        self.vehicle_status_pub = rospy.Publisher(
            'vehicle_status', VehicleStatus, queue_size=1)

        # Subscribers
        rospy.Subscriber('/carla/ego_vehicle/vehicle_status', CarlaEgoVehicleStatus,
                         self.vehicle_status_callback, queue_size=1)
        rospy.Subscriber('/carla/ego_vehicle/vehicle_info', CarlaEgoVehicleInfo,
                         self.vehicle_info_callback, queue_size=1)

    def vehicle_info_callback(self, data):
        """
        callback for vehicle info
        """
        # get max steering angle (use smallest non-zero value of all wheels)
        for wheel in data.wheels:
            if wheel.max_steer_angle and wheel.max_steer_angle < self.max_steer_angle:
                self.max_steering_angle = wheel.max_steer_angle

    def vehicle_status_callback(self, data):
        """
        callback for vehicle status
        """

        status = VehicleStatus()
        status.header = data.header

        status.angle = data.control.steer * math.degrees(self.max_steer_angle)
        status.speed = data.velocity * 3.6  # speed is expected in km/h

        if data.control.reverse:
            status.current_gear.gear = Gear.REVERSE
        else:
            status.current_gear.gear = Gear.DRIVE

        if data.control.manual_gear_shift:
            status.drivemode = VehicleStatus.MODE_MANUAL
        else:
            status.drivemode = VehicleStatus.MODE_AUTO

        self.vehicle_status_pub.publish(status)

    def run(self):
        rospy.spin()


if __name__ == '__main__':
    rospy.init_node('carla_vehicle_status_publisher', log_level=rospy.INFO, anonymous=False)
    node = CarlaVehicleStatusPublisher()
    node.run()
