#!/usr/bin/env python
#
# Copyright (c) 2019 Intel Corporation
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.
"""
receive nav_msgs::Odometry and publish geometry_msgs::PoseStamped
"""
import rospy
from geometry_msgs.msg import PoseStamped
from nav_msgs.msg import Odometry


class OdometryToPoseStamped:
    def __init__(self):

        # Node parameters
        role_name = rospy.get_param('/carla/role_name', default='ego_vehicle')

        # Subscribers
        rospy.Subscriber('/carla/odometry'.format(role_name),
                         Odometry, self.odometry_callback)

        # Publishers
        self.pose_pub = rospy.Publisher('gnss_pose', PoseStamped, queue_size=1)

    def odometry_callback(self, data):
        """
        callback for current pose
        """
        pose = PoseStamped()
        pose.header = data.header
        pose.pose = data.pose.pose
        self.pose_pub.publish(pose)

    def run(self):
        rospy.spin()


if __name__ == '__main__':
    rospy.init_node('odometry_to_pose_stamped', log_level=rospy.INFO, anonymous=False)
    node = OdometryToPoseStamped()
    node.run()
