coordinate_transformer: utm         # utm, lest97
use_custom_origin: True
utm_origin_lat: 0.0
utm_origin_lon: 0.0
lest97_origin_northing: 6465000.0
lest97_origin_easting: 650000.0

novatel_oem7_localizer:
  use_msl_height: True
  child_frame: base_link
