lanelet2_global_planner:
  output_frame: map
  distance_to_centerline_limit: 5.0
  speed_limit: 40.0                   # max velocity for route (km/h), will be replaced by speed taken from map

waypoint_loader:
  output_frame: map
  wp_left_width: 1.4
  wp_right_width: 1.4

waypoint_saver:
  interval: 1.0

path_smoothing:
  waypoint_interval: 1.0                  # m
  adjust_speeds_in_curves: True
  adjust_speeds_using_deceleration: True
  speed_deceleration_limit: 1.0           # m/s2
  radius_calc_neighbour_index: 4          # int
  lateral_acceleration_limit: 3.0         # m/s2